export const FETCH_ADMIN_PROFILE_LOADING = "FETCH_ADMIN_PROFILE_LOADING";
export const FETCH_ADMIN_PROFILE_SUCCESS = "FETCH_ADMIN_PROFILE_SUCCESS";
export const FETCH_ADMIN_PROFILE_FAIL = "FETCH_ADMIN_PROFILE_FAIL";
