export const ADD_TO_CART = "ADD_TO_CART";
export const UPDATE_CART= "UPDATE_CART";
export const SET_CART_TOTAL = "SET_CART_TOTAL";

export const DELETE_CART = "DELETE_CART";
export const FETCH_PROFILE_LOADING = "FETCH_PROFILE_LOADING";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_FAIL = "FETCH_PROFILE_FAIL";
export const FETCH_CART_LOADING = "FETCH_CART_LOADING";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const FETCH_CART_FAIL = "FETCH_CART_FAIL";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";